### ISSUE TITLE
figure out a better way to track the agreement dates

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-google-app#5]
(TODAY vs the actual signed date in the spreadsheet.)

when a spreadsheet is actually signed, we should detect that using the appropriate signature-engine adapter, and record the new date into the spreadsheet.

**Comment by mengwong** [comment]
there are two parts to this -- every agreement should have a unique variable name for its signing date.
when an agreement is created, we should record that date as a provisional, right in the spreadsheet.
when we notice that the e-signature system has recorded a signature complete state for the agreement, we promote the provisional to confirmed.

i think the way to do this is we create a _provisional extension to each whatever_agreement_date.

**Comment by mengwong** [comment]
also think about amendments and restatements.

**Comment by jobchong** [comment]
This issue was moved to legalese-io/legalese-io.github.io#132
